version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: unless-stopped

