version: '3'

services:
  db:
    image: postgres:13.1
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - "./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgresdata:
    driver: local