name: Continous Integration
on:
  push:
    branches:
      - branch/ci

jobs:
  unit_testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build database
        run: |
          docker-compose up --build -d
          docker exec -it  postgres_container psql -U root -c 'CREATE DATABASE todolist'

      - name : Building the project
        run: |
          npm install
          npm run build
          npm run start

      - name: Unit testing
        run: npm run test
